In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.utils import resample
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier

# Feature Importance - Aplicar ao algoritmo Random Forest e determinar quais features do dataset são mais importantes para o problema;

##Lembrete:

- Aplicar a normalização nos dados e verificar os efeitos nos modelos;


# Random Forest - Vinho Vermelho

In [ ]:
df = pd.read_csv('/content/winequality.csv')
df = df.drop(columns='Unnamed: 0')
df.head()

fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  wine_is_red
0            5.9              0.61         0.08  ...     11.1        6            1
1            8.2              1.00         0.09  ...      9.0        6            1
2            6.4              0.24         0.49  ...     10.5        6            0
3            6.6              0.23         0.26  ...     10.0        6            0
4            7.2              0.24         0.29  ...     10.1        6            0

[5 rows x 13 columns]

In [ ]:
df.wine_is_red.value_counts()

0    4898
1    1599
Name: wine_is_red, dtype: int64

In [ ]:
# igualizando o número de observações de cada classe

df_red = df[df.wine_is_red==1]
df_white = df[df.wine_is_red==0]

df_white = resample(df_white, replace = False, n_samples = 1599)

df = pd.concat([df_white,df_red])

df.wine_is_red.value_counts()

1    1599
0    1599
Name: wine_is_red, dtype: int64

In [ ]:
# normalizando:

for i in df.columns:
  df[i] = (df[i] - df[i].min()) / (df[i].max() - df[i].min())

df.head()

fixed acidity  volatile acidity  ...   quality  wine_is_red
3478       0.283333          0.146667  ...  0.333333          0.0
1090       0.291667          0.086667  ...  0.666667          0.0
3953       0.325000          0.053333  ...  0.500000          0.0
4748       0.350000          0.120000  ...  0.500000          0.0
2011       0.291667          0.120000  ...  0.500000          0.0

[5 rows x 13 columns]

In [ ]:
# separando em treino e teste

x = df.drop(columns='wine_is_red')
y = df.wine_is_red

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, shuffle = True)

In [ ]:
clf = RandomForestClassifier(n_jobs = 2, random_state = 14)

clf.fit(x_train,y_train)

RandomForestClassifier(n_jobs=2, random_state=14)

In [ ]:
y_pred = clf.predict(x_test)
y_pred[0:25]

array([0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 0., 1., 1., 1., 1., 0.])

In [ ]:
clf.predict_proba(x_test)[0:20]

array([[1.  , 0.  ],
       [1.  , 0.  ],
       [0.02, 0.98],
       [0.  , 1.  ],
       [0.86, 0.14],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.01, 0.99],
       [0.  , 1.  ],
       [0.01, 0.99],
       [1.  , 0.  ],
       [0.98, 0.02],
       [0.99, 0.01],
       [0.01, 0.99],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.99, 0.01],
       [0.02, 0.98],
       [0.04, 0.96],
       [1.  , 0.  ]])

In [ ]:
tabela = pd.crosstab(y_test,y_pred, rownames = [''], colnames = [''])

print(f'A acurácia do algoritmo de Random Forest foi de {round(accuracy_score(y_test,y_pred)*100,3)}% \n {tabela}') 
# confusion matrix e precision

A acurácia do algoritmo de Random Forest foi de 99.5% 
      0.0  1.0
             
0.0  393    0
1.0    0  407


In [ ]:
tabela # não plotou direito os erros, mas foram exatos 3 erros

0.0  1.0
             
0.0  393    0
1.0    0  407

In [ ]:
feature_list = list(x.columns)
# Conseguindo as importancias das variáveis
importances = list(clf.feature_importances_)
# Lista de tuplas das variaveis e sua importancia
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]
# Sorteando as variáveis por ordem decrescente de mais importante
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)
# Printando
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

Variable: chlorides            Importance: 0.29
Variable: total sulfur dioxide Importance: 0.23
Variable: volatile acidity     Importance: 0.13
Variable: density              Importance: 0.08
Variable: free sulfur dioxide  Importance: 0.07
Variable: sulphates            Importance: 0.07
Variable: residual sugar       Importance: 0.06
Variable: fixed acidity        Importance: 0.03
Variable: citric acid          Importance: 0.02
Variable: pH                   Importance: 0.02
Variable: alcohol              Importance: 0.01
Variable: quality              Importance: 0.0


As três variáveis mais importantes para o modelo são Chlorides, Total Sulfur dioxide e Volatile acidity, somando 65%

# Support Vector Machine

o SVM será utilizado na mesma aplicação do random forest

In [ ]:
from sklearn import preprocessing, svm

In [ ]:
clf = svm.SVC()
clf.fit(x_train,y_train)

SVC()

In [ ]:
print(f'A acurácia do algoritmo de Support Vector Machine foi de {round(clf.score(x_test,y_test)*100,2)}%')

A acurácia do algoritmo de Support Vector Machine foi de 99.38%


# Aplicar um dos métodos de Ensemble Learning e comparar os resultados.

##Lembrete:

- Aplicar as técnicas de undersampling e oversampling nos dados. Verificar e explicar os efeitos;

In [ ]:
df = pd.read_csv('/content/winequality.csv')
df = df.drop(columns='Unnamed: 0')
df.head()

fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  wine_is_red
0            5.9              0.61         0.08  ...     11.1        6            1
1            8.2              1.00         0.09  ...      9.0        6            1
2            6.4              0.24         0.49  ...     10.5        6            0
3            6.6              0.23         0.26  ...     10.0        6            0
4            7.2              0.24         0.29  ...     10.1        6            0

[5 rows x 13 columns]

In [ ]:
df.quality.value_counts()

6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: quality, dtype: int64

## Undersampling:

In [ ]:
# UNDERSAMPLING: vamos retirar as classificações 9 e 3, já que possuem poucas observações e foi visto na parte 1 que ajuda na precisão do algoritmo
#df_9 = df[df.quality==9]
#df_3 = df[df.quality==3]
df_8 = df[df.quality==8]
df_4 = df[df.quality==4]
df_7 = df[df.quality==7]
df_5 = df[df.quality==5]
df_6 = df[df.quality==6]

In [ ]:
df_8 = resample(df_8, replace = False, n_samples = 193)
df_4 = resample(df_4, replace = False, n_samples = 193)
df_7 = resample(df_7, replace = False, n_samples = 193)
df_5 = resample(df_5, replace = False, n_samples = 193)
df_6 = resample(df_6, replace = False, n_samples = 193)

df = pd.concat([df_8,df_4,df_7,df_5,df_6])

df.quality.value_counts()

8    193
7    193
6    193
5    193
4    193
Name: quality, dtype: int64

In [ ]:
# normalizando:

for i in df.drop(columns='quality').columns:
  df[i] = (df[i] - df[i].min()) / (df[i].max() - df[i].min())

df.head()

fixed acidity  volatile acidity  ...  quality  wine_is_red
4678       0.258621          0.245098  ...        8          0.0
6169       0.250000          0.254902  ...        8          0.0
6240       0.129310          0.411765  ...        8          0.0
2262       0.267241          0.107843  ...        8          0.0
2598       0.112069          0.323529  ...        8          0.0

[5 rows x 13 columns]

In [ ]:
# Separando nosso df em treino e teste:

x = df.drop(columns='quality')
y = df.quality

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, shuffle = True)

x_train = np.array(x_train) 
x_test = np.array(x_test) 
y_train = np.array(y_train) 
y_test = np.array(y_test)

In [ ]:
rf = RandomForestClassifier(n_estimators = 1000, random_state = 14)

rf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=1000, random_state=14)

In [ ]:
y_pred = rf.predict(x_test)

print(f'{y_test[0:10]} \n {y_pred[0:10]}')

[5 7 5 7 4 5 4 5 7 4] 
 [6 7 4 8 4 5 4 4 6 4]


In [ ]:
print(f'A precisão do algoritmo para classificação multiclasse é de {round(accuracy_score(y_test,y_pred)*100,3)}%')

A precisão do algoritmo para classificação multiclasse é de 48.347%


In [ ]:
feature_list = list(x.columns)
# Conseguindo as importancias das variáveis
importances = list(rf.feature_importances_)
# Lista de tuplas das variaveis e sua importancia
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]
# Sorteando as variáveis por ordem decrescente de mais importante
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)
# Printando
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

# Vimos que não há uma variável bem mais importante que a outra, estão, no geral, bem balanceadas (menos wine_is_red)

Variable: alcohol              Importance: 0.12
Variable: volatile acidity     Importance: 0.1
Variable: free sulfur dioxide  Importance: 0.1
Variable: chlorides            Importance: 0.09
Variable: total sulfur dioxide Importance: 0.09
Variable: density              Importance: 0.09
Variable: sulphates            Importance: 0.09
Variable: fixed acidity        Importance: 0.08
Variable: citric acid          Importance: 0.08
Variable: residual sugar       Importance: 0.08
Variable: pH                   Importance: 0.07
Variable: wine_is_red          Importance: 0.01


## Oversampling:

In [ ]:
from imblearn.over_sampling import RandomOverSampler 

In [ ]:
df = pd.read_csv('/content/winequality.csv')
df = df.drop(columns='Unnamed: 0')
df.head()

fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  wine_is_red
0            5.9              0.61         0.08  ...     11.1        6            1
1            8.2              1.00         0.09  ...      9.0        6            1
2            6.4              0.24         0.49  ...     10.5        6            0
3            6.6              0.23         0.26  ...     10.0        6            0
4            7.2              0.24         0.29  ...     10.1        6            0

[5 rows x 13 columns]

In [ ]:
df.quality.value_counts()

6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: quality, dtype: int64

In [ ]:
# OVERSAMPLING: vamos repetir as classificações 9 e 3, já que possuem poucas observações para podermos aplicar o algoritmo
df_9 = df[df.quality==9]
df_3 = df[df.quality==3]
df_8 = df[df.quality==8]
df_4 = df[df.quality==4]
df_7 = df[df.quality==7]
df_5 = df[df.quality==5]
df_6 = df[df.quality==6]

In [ ]:
df_8 = resample(df_8, replace = False, n_samples = 193)
df_4 = resample(df_4, replace = False, n_samples = 193)
df_7 = resample(df_7, replace = False, n_samples = 193)
df_5 = resample(df_5, replace = False, n_samples = 193)
df_6 = resample(df_6, replace = False, n_samples = 193)

df = pd.concat([df_8,df_4,df_7,df_5,df_6,df_9,df_3])

df.quality.value_counts()

8    193
7    193
6    193
5    193
4    193
3     30
9      5
Name: quality, dtype: int64

In [ ]:
# normalizando:

for i in df.drop(columns='quality').columns:
  df[i] = (df[i] - df[i].min()) / (df[i].max() - df[i].min())

df.head()

fixed acidity  volatile acidity  ...  quality  wine_is_red
4548       0.293103          0.081633  ...        8          0.0
4588       0.241379          0.149660  ...        8          0.0
390        0.293103          0.204082  ...        8          0.0
4777       0.112069          0.119048  ...        8          0.0
1466       0.362069          0.040816  ...        8          0.0

[5 rows x 13 columns]

In [ ]:
# Separando nosso df em treino e teste:

x = df.drop(columns='quality')
y = df.quality

In [ ]:
oversample = RandomOverSampler(sampling_strategy='minority')

x_over, y_over = oversample.fit_resample(x, y)

x_over, y_over = oversample.fit_resample(x_over, y_over) # repetindo para que a qualidade 3 também tenha 193 obs

In [ ]:
y_over.value_counts()

9    193
8    193
7    193
6    193
5    193
4    193
3    193
Name: quality, dtype: int64

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_over, y_over, test_size=0.25, shuffle = True)

x_train = np.array(x_train) 
x_test = np.array(x_test) 
y_train = np.array(y_train) 
y_test = np.array(y_test)

In [ ]:
rf = RandomForestClassifier(n_estimators = 1000, random_state = 14)

rf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=1000, random_state=14)

In [ ]:
y_pred = rf.predict(x_test)

print(f'{y_test[0:10]} \n {y_pred[0:10]}')

[6 8 6 3 7 5 9 4 8 3] 
 [5 6 7 3 7 5 9 4 8 3]


In [ ]:
print(f'A precisão do algoritmo para classificação multiclasse é de {round(accuracy_score(y_test,y_pred)*100,3)}%') # a precisão subiu de 48% para 61%!

A precisão do algoritmo para classificação multiclasse é de 61.243%


Utilizando a técnica de oversampling na variável Quality, tanto na categoria 9 quanto na 3 (que eram as com menos observações), a precisão do modelo subiu de 48% para 61%

In [ ]:
feature_list = list(x_over.columns)
# Conseguindo as importancias das variáveis
importances = list(rf.feature_importances_)
# Lista de tuplas das variaveis e sua importancia
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]
# Sorteando as variáveis por ordem decrescente de mais importante
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)
# Printando
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

# Vimos que não há uma variável bem mais importante que a outra, estão, no geral, bem balanceadas (menos wine_is_red)

Variable: density              Importance: 0.11
Variable: alcohol              Importance: 0.11
Variable: fixed acidity        Importance: 0.1
Variable: chlorides            Importance: 0.1
Variable: free sulfur dioxide  Importance: 0.1
Variable: volatile acidity     Importance: 0.08
Variable: residual sugar       Importance: 0.08
Variable: total sulfur dioxide Importance: 0.08
Variable: pH                   Importance: 0.08
Variable: citric acid          Importance: 0.07
Variable: sulphates            Importance: 0.07
Variable: wine_is_red          Importance: 0.01
